apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: octo
  namespace: agent-octo
spec:
  components:
    db: {}
    realtime: {}
    storage:
      install_minio: true
      max_upload_size: 50mb
  profiles:
    dev:
      components:
        oidc:
          hostname-url: http://localhost:30060
        ingress:
          port: 30060
        db:
          expose_db_port: 30061
  services:
    web:
      image: ghcr.io/purton-tech/octo:1.0.1
      port: 3000
      database_url: APPLICATION_URL
      init:
        image: ghcr.io/purton-tech/octo-migrations:1.0.1
        migrations_database_url: DATABASE_URL
    agent-runtime:
      image: ghcr.io/purton-tech/agent-runtime:1.0.1
      migrations_database_url: DATABASE_URL
    telegram-egress:
      image: ghcr.io/purton-tech/telegram-egress:1.0.1
      migrations_database_url: DATABASE_URL
    telegram-ingress-polling:
      image: ghcr.io/purton-tech/telegram-ingress-polling:1.0.1
      migrations_database_url: DATABASE_URL:Ex
