apiVersion: stack-cli.dev/v1
kind: StackApp
metadata:
  name: octo
  namespace: agent-octo
spec:
  components:
    db: {}
  profiles:
    dev:
      components:
        ingress:
          port: 30060
        db:
          expose_db_port: 30061
  services:
    web:
      image: mendhak/http-https-echo:1.0.0
      port: 8080
      database_url: DATABASE_URL